[package]
name = "baseball"
version = "0.2.0"
authors = ["Eli Ben-Porat <eli.bp@jottabyte.io>"]
edition = "2018"

[dependencies]
reqwest = "0.9.9"
serde = {version = "1.0", features = ["derive"]}
serde-xml-rs = "0.3.1"
rayon = "1.1.0"
regex = "1"

csv = "1.1"
